<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>winstate</AssemblyName>
    <RootNamespace>WinState.Cli</RootNamespace>
    <Version>0.5.0-alpha.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WinState.App\WinState.App.csproj" />
    <ProjectReference Include="..\WinState.Terminal\WinState.Terminal.csproj" />
  </ItemGroup>
</Project>
