schemaVersion: 1

metadata:
  name: Base Developer Environment
  description: Общие значения для рабочих станций

variables:
  toolsRoot: ./tools

environment:
  user:
    WINSTATE_MANAGED: "true"
  userPath:
    - path: "{{toolsRoot}}/bin"
      state: present
      position: prepend
