<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Безопасное управление переменными окружения и PATH в Windows.</Description>
    <RootNamespace>WinState.Providers.EnvironmentVariables</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WinState.Domain\WinState.Domain.csproj" />
  </ItemGroup>
</Project>
