<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\WinState.App\WinState.App.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Spectre.Console" />
  </ItemGroup>
  <PropertyGroup>
    <Description>Интерактивная консольная панель WinState.</Description>
  </PropertyGroup>
</Project>
